### ISSUE TITLE
Won't start, missing files, outdated guide?

### ISSUE THREAD

**Issue by dylanh724** [KockaAdmiralac/WikiaActivityLogger#17]
json.config is ready at "/"
Calling `sudo ./scripts/start.sh`
results in:

```
npm ERR! Linux 3.13.0-77-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.2
npm ERR! path /home/dylan/discord/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/dylan/discord/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/dylan/discord/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dylan/discord/npm-debug.log
dylan@api:~/discord/WikiaActivityLogger$
```

**Comment by KockaAdmiralac** [comment]
Oh, right. That's because start.sh goes to the parent directory before running main.js. Try going into the `scripts` directory (`cd scripts`) and then running start.sh

I think I should include that in the guide or try to fix the script (somehow, I'm not too good in Bash), thanks for pointing that out!

**Comment by dylanh724** [comment]
Cool thanks ;D while that worked, I ran into a new error:

```
> wikia-activity-logger@1.5.2 start /home/dylan/discord/WikiaActivityLogger
> node index.js


=====
Welcome to wikia-activity-logger v1.5.2!
Documentation can be found at http://dev.wikia.com/wiki/WikiaActivityLogger
=====

An error occurred while loading the configuration! Please make sure config.json file in the main directory exists. (Logger._initConfig)
An error occurred while initializing cache. If this is your first time starting WikiaActivityLogger, ignore this error. (Logger._initCache)
/home/dylan/discord/WikiaActivityLogger/main.js:87
        if(this._config.no_updates) {
                       ^

TypeError: Cannot read property 'no_updates' of undefined
    at Logger._checkForUpdates (/home/dylan/discord/WikiaActivityLogger/main.js:87:24)
    at Logger.initialize (/home/dylan/discord/WikiaActivityLogger/main.js:34:14)
    at CLI.initialize (/home/dylan/discord/WikiaActivityLogger/controllers/controller.js:25:19)
    at Object.<anonymous> (/home/dylan/discord/WikiaActivityLogger/index.js:22:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
```
It says config.json file in main dir must exist, but it's there:

![image](https://cloud.githubusercontent.com/assets/8840024/24891800/bf6bc1e8-1eaa-11e7-9d14-e18094035424.png)

**Comment by dylanh724** [comment]
Hmm.... I looked through the file. Seems like config.json needs a "no_updates" entry? I couldn't find anythng about it on the guide, though. I tried manually adding it, didn't help. I tried commenting out the entire updates section, didn't help.

When I tried commenting out the update part, it couldn't find "accounts" either (which definitely exists. JSON lint passed too). **So seems that the _config var never actually picks up the config file. The _config var is null.**

Any help would be appreciated when you have time ;D seems like I did everything correctly.

**Comment by KockaAdmiralac** [comment]
The error there is that it failed to load the configuration file, everything else is a result of that. Only reasons for that fail I can think of are
- config.json doesn't exist (but it does)
- WikiaActivityLogger doesn't have permission to read that file (that shouldn't be an issue since you're running WikiaActivityLogger as superuser)
- The file is improperly formatted (try using a JSON validator such as [this one](https://jsonformatter.curiousconcept.com) to verify your file is properly formatted)

Is any of these the reason?

**Comment by dylanh724** [comment]
> JSON lint passed too

yep linted and passed, Yea superuser / config does exist =( I don't believe these are the issues.

It's like you said, the initial load to read the config file is picking up null. Some type of read err?

**Comment by KockaAdmiralac** [comment]
Weird. Can you try replacing [this line](https://github.com/KockaAdmiralac/WikiaActivityLogger/blob/master/main.js#L45) with `main.hook('throw', e);` and check the stack trace?
