### ISSUE TITLE
There was an included API key or something

### ISSUE THREAD

**Issue by dylanh724** [KockaAdmiralac/WikiaActivityLogger#18]
Careful ~ it's public (in config.json.sample). **It wasn't in the guide,** so I'm wondering if it was experimental and accidentally left in.

**Comment by KockaAdmiralac** [comment]
You mean [these two lines](https://github.com/KockaAdmiralac/WikiaActivityLogger/blob/master/config.sample.json#L6-L7)? Those are just examples, that webhook [doesn't actually work](https://discordapp.com/api/webhooks/123456789/aosBaAodia-oIA9DAkasd-9jASdlkAdu-7Askanadki-IASd8Asnak).

**Comment by Colouratura** [comment]
This should be closed no?
