### ISSUE TITLE
undefined vundefined successfully initialized!

### ISSUE THREAD

**Issue by dylanh724** [KockaAdmiralac/WikiaActivityLogger#33]
![image](https://user-images.githubusercontent.com/8840024/31055632-79f2fd30-a6f8-11e7-9469-1e03da9d03fc.png)
This bug has been here for a while - just never reported it. 

It seems that it only shows a successful "normal" startup on an update?

**Comment by KockaAdmiralac** [comment]
You did report it in #30, though. Can you update to 1.5.9? #32 should've fixed that.

**Comment by dylanh724** [comment]
Oops, I forgot I had! Been a while. Update seems to have fixed it~
