### ISSUE TITLE
Can't seem to add Korean (ko)

### ISSUE THREAD

**Issue by dylanh724** [KockaAdmiralac/WikiaActivityLogger#34]
If I add Korean (ko.somewikia), I can't start the app:

![image](https://user-images.githubusercontent.com/8840024/31055652-bcd03122-a6f8-11e7-88b0-0ada4b45abbb.png)

As soon as I remove the Korean entry, it works again ~

**Comment by KockaAdmiralac** [comment]
That is weird. Can you run your `config.json` through a JSON linter to ensure it's valid JSON?

**Comment by dylanh724** [comment]
Sorry mate, looks like it WAS not a valid json, gah. My bad ;)
