### ISSUE TITLE
Throwing HTTP 403 errors

### ISSUE THREAD

**Issue by KockaAdmiralac** [KockaAdmiralac/WikiaActivityLogger#43]
The issue is on Wikia's side and it is unknown if it will be fixed. A new tool is being worked on, contact me if you want to get your already existent logger working again.

**Comment by dylanh724** [comment]
@KockaAdmiralac I'd like to get my already-existent logger working again. What do I do? Do you have Discord?

![image](https://user-images.githubusercontent.com/8840024/42617919-03664104-85e6-11e8-8185-1284c8149167.png)

**Comment by KockaAdmiralac** [comment]
I do, `KockaAdmiralac#9306`.
